### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [hectorm/hblock-resolver#1]
hi sir. this is the project you mean. I am happy to design the logo for this project. I will design the logo. you can wait for it. thanks sir.

**Comment by mansya** [comment]
hi sir. I have design logo for this project. what do you think ? do you like it ? if you like, wich one do you like it ?

![hblock resolver](https://user-images.githubusercontent.com/33461607/43671317-bf729996-97c1-11e8-898a-d70d14970d1f.png)

**Comment by hectorm** [comment]
Sorry, but as I mentioned in https://github.com/hectorm/hmirror/issues/2#issuecomment-410290419, the design should be consistent with the [hBlock logo](https://github.com/hectorm/hblock/tree/master/resources/logo). The font must be the same (Source Sans Pro) and the shape may be different from a shield but must follow the same style.

In any case, thanks for your work, it is always a pleasure to receive contributions in a disinterested way.

**Comment by desuto** [comment]
I will fix this sir. Thanks

**Comment by mansya** [comment]
I will fix this sir. Thanks

**Comment by mansya** [comment]
Hi sir. what do you think about this ?
![hblock resolver](https://user-images.githubusercontent.com/33461607/43692313-0dae932c-9951-11e8-858a-1123533ca5ca.png)

**Comment by hectorm** [comment]
Sorry, but the style is still not consistent with hBlock and I do not think it fits into this project.
Anyway, I'm going to pause this because I have a trip soon and I will be offline for a few weeks.

**Comment by mansya** [comment]
I will fix it. no problem with your trip. You can contribute again when you have free time. enjoy your trip sir

**Comment by mansya** [comment]
hi sir. if you are online again. You can give feedback about this repair logo. if there is no improvement, you can choose the one you like.

![new hblock resolver](https://user-images.githubusercontent.com/33461607/43991660-17ba0c9e-9d9c-11e8-92f4-3bdfb3698f35.png)

**Comment by hectorm** [comment]
Sorry, I have other plans for the logo. Probably in the future I will end up doing it myself. Thanks for your time.
